version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: foodtravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  backend_app:
    build: .
    container_name: foodtravel_backend
    ports:
      - "3000:3000"
    environment:
     
      DB_HOST: mysql_db
      DB_USER: ${DB_USER}        
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}        
      PORT: ${PORT}
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  db_data: